# Generated by Django 5.2 on 2025-07-30 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('contracts', '0002_init_sharhkhadamat_tabels'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accessible_contracts_denorm',
            field=models.ManyToManyField(blank=True, help_text='این فیلد به صورت خودکار بروزرسانی می\u200cشود', related_name='users_with_access', to='contracts.contract', verbose_name='قراردادهای قابل دسترسی'),
        ),
        migrations.CreateModel(
            name='UserShrhLayerPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('shrh_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.shrhlayer', verbose_name='لایه شرح خدمات')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دسترسی کاربر به لایه',
                'verbose_name_plural': 'دسترسی\u200cهای کاربران به لایه\u200cها',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='accessible_shrh_layers',
            field=models.ManyToManyField(blank=True, related_name='accessible_by_users', through='accounts.UserShrhLayerPermission', to='contracts.shrhlayer', verbose_name='لایه\u200cهای قابل دسترسی'),
        ),
        migrations.AddIndex(
            model_name='usershrhlayerpermission',
            index=models.Index(fields=['user'], name='accounts_us_user_id_b8b74f_idx'),
        ),
        migrations.AddIndex(
            model_name='usershrhlayerpermission',
            index=models.Index(fields=['shrh_layer'], name='accounts_us_shrh_la_9a34ec_idx'),
        ),
        migrations.AddIndex(
            model_name='usershrhlayerpermission',
            index=models.Index(fields=['user', 'shrh_layer'], name='accounts_us_user_id_33ea6e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usershrhlayerpermission',
            unique_together={('user', 'shrh_layer')},
        ),
    ]
