# Generated by Django 5.2 on 2025-08-04 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_shrlayer_accessable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'ابزار دسترسی',
                'verbose_name_plural': 'ابزارهای دسترسی',
            },
        ),
        migrations.CreateModel(
            name='Apis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=50)),
                ('url', models.CharField(max_length=250)),
                ('desc', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'نام دسترسی',
                'verbose_name_plural': 'لیست  دسترسی ها',
                'unique_together': {('method', 'url')},
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('desc', models.CharField(blank=True, max_length=250, null=True)),
                ('apis', models.ManyToManyField(related_name='rrolesapis', related_query_name='rolesapis', to='accounts.apis')),
                ('tools', models.ManyToManyField(blank=True, related_name='rroletools', related_query_name='roletools', to='accounts.tools')),
            ],
            options={
                'verbose_name': 'نام نقش',
                'verbose_name_plural': 'لیست نقش ها',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rrole', to='accounts.roles'),
        ),
    ]
