# Generated by Django 5.2 on 2025-08-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_api_too_role_to_user'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='apis',
            index=models.Index(fields=['method', 'url'], name='accounts_ap_method_b01f96_idx'),
        ),
        migrations.AddIndex(
            model_name='apis',
            index=models.Index(fields=['url'], name='accounts_ap_url_b0c98c_idx'),
        ),
        migrations.AddIndex(
            model_name='apis',
            index=models.Index(fields=['method'], name='accounts_ap_method_d5cb30_idx'),
        ),
    ]
