# Generated by Django 5.2 on 2025-08-05 05:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_index_to_url_and_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='url',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(message='فرمت URL نادرست است. باید با / شروع شود و فقط شامل حروف، اعداد، /، - و _ باشد.', regex='^\\/[a-zA-Z0-9_\\-\\/]*\\/?$')]),
        ),
    ]
