# Generated by Django 5.2 on 2025-09-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_company_to_user'),
        ('contracts', '0015_make_conbrdr_in_shrlyr_notnull'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accessible_contractborders_denorm',
            field=models.ManyToManyField(blank=True, help_text='این فیلد به صورت خودکار بروزرسانی می\u200cشود', related_name='users_with_access_borders', to='contracts.contractborder', verbose_name='محدوده\u200cهای قرارداد قابل دسترسی'),
        ),
    ]
