# Generated by Django 5.2 on 2025-09-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_contractborder_denorm'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_controller',
            field=models.BooleanField(default=False, help_text='نشان می\u200cدهد که آیا این کاربر کنترل کننده پروژه است یا خیر', verbose_name='کنترل کننده است؟'),
        ),
    ]
