# Generated by Django 5.2 on 2025-11-19 08:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_is_controller_to_user'),
        ('contracts', '0017_user_objectlevel_permission'),
        ('initialborders', '0003_add_m2mrel_initialborder_prviance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='accessible_contractborders_denorm',
        ),
        migrations.RemoveField(
            model_name='user',
            name='accessible_contracts_denorm',
        ),
        migrations.AlterField(
            model_name='apis',
            name='url',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(message='فرمت URL نادرست است. باید با / شروع شود و فقط شامل حروف، اعداد، /، -، _ و {} باشد.', regex='^\\/[a-zA-Z0-9_\\-\\/\\{\\}]*\\/?$')]),
        ),
        migrations.CreateModel(
            name='UserContractBorderPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractborder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contractborder', verbose_name='محدوده قرارداد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دسترسی کاربر به محدوده قرارداد',
                'verbose_name_plural': 'دسترسی\u200cهای کاربران به محدوده\u200cهای قرارداد',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='accessible_contractborders',
            field=models.ManyToManyField(blank=True, help_text='این فیلد به صورت خودکار بروزرسانی می\u200cشود', related_name='users_with_access_contractborders', through='accounts.UserContractBorderPermission', to='contracts.contractborder', verbose_name='محدوده\u200cهای قرارداد قابل دسترسی'),
        ),
        migrations.CreateModel(
            name='UserContractPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='قرارداد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دسترسی کاربر به قرارداد',
                'verbose_name_plural': 'دسترسی\u200cهای کاربران به قراردادها',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='accessible_contracts',
            field=models.ManyToManyField(blank=True, help_text='این فیلد به صورت خودکار بروزرسانی می\u200cشود', related_name='users_with_access_contracts', through='accounts.UserContractPermission', to='contracts.contract', verbose_name='قراردادهای قابل دسترسی'),
        ),
        migrations.CreateModel(
            name='UserInitialBorderPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initialborder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initialborders.initialborder', verbose_name='محدوده اولیه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دسترسی کاربر به محدوده اولیه',
                'verbose_name_plural': 'دسترسی\u200cهای کاربران به محدوده\u200cهای اولیه',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='accessible_initialborders',
            field=models.ManyToManyField(blank=True, related_name='users_with_access_initialborders', through='accounts.UserInitialBorderPermission', to='initialborders.initialborder', verbose_name='محدوده\u200cهای اولیه قابل دسترسی'),
        ),
        migrations.AddIndex(
            model_name='usercontractborderpermission',
            index=models.Index(fields=['user'], name='accounts_us_user_id_24e3b0_idx'),
        ),
        migrations.AddIndex(
            model_name='usercontractborderpermission',
            index=models.Index(fields=['contractborder'], name='accounts_us_contrac_cd5751_idx'),
        ),
        migrations.AddIndex(
            model_name='usercontractborderpermission',
            index=models.Index(fields=['user', 'contractborder'], name='accounts_us_user_id_efb2ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usercontractborderpermission',
            unique_together={('user', 'contractborder')},
        ),
        migrations.AddIndex(
            model_name='usercontractpermission',
            index=models.Index(fields=['user'], name='accounts_us_user_id_f9b8e9_idx'),
        ),
        migrations.AddIndex(
            model_name='usercontractpermission',
            index=models.Index(fields=['contract'], name='accounts_us_contrac_e61905_idx'),
        ),
        migrations.AddIndex(
            model_name='usercontractpermission',
            index=models.Index(fields=['user', 'contract'], name='accounts_us_user_id_637b5c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usercontractpermission',
            unique_together={('user', 'contract')},
        ),
        migrations.AddIndex(
            model_name='userinitialborderpermission',
            index=models.Index(fields=['user'], name='accounts_us_user_id_a5e13c_idx'),
        ),
        migrations.AddIndex(
            model_name='userinitialborderpermission',
            index=models.Index(fields=['initialborder'], name='accounts_us_initial_4e8f5b_idx'),
        ),
        migrations.AddIndex(
            model_name='userinitialborderpermission',
            index=models.Index(fields=['user', 'initialborder'], name='accounts_us_user_id_af498e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userinitialborderpermission',
            unique_together={('user', 'initialborder')},
        ),
    ]
