# Generated by Django 5.2 on 2025-12-15 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_objectlevel_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='codemeli',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='user',
            name='end_access',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پایان دسترسی'),
        ),
        migrations.AddField(
            model_name='user',
            name='fax',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='فکس'),
        ),
        migrations.AddField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='شماره تماس باید با 989 شروع شود و دقیقاً 12 رقم باشد.', regex='^989\\d{9}$')], verbose_name='شماره تماس'),
        ),
        migrations.AddField(
            model_name='user',
            name='start_access',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ شروع دسترسی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'کاربر با این نام کاربری موجود است'}, help_text='اجباری.کمتر از 25 کاراکتر. فقط حروف و اعداد استفاده کنید', max_length=25, unique=True, validators=[django.core.validators.RegexValidator(message='فقط حروف و اعداد استفاده کنید', regex='^[0-9a-zA-Z]*$')], verbose_name='username'),
        ),
    ]
