# Generated by Django 5.2 on 2025-12-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_new_fields_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_attempt_login_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
