# Generated by Django 5.2 on 2025-07-20 05:21

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import initialborders.models.attachment
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialBorderAttachmentDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(error_messages={'unique': 'کد پیوست باید یکتا باشد.'}, unique=True, verbose_name='کد پیوست')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان نوع پیوست')),
                ('category', models.CharField(max_length=100, verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'نوع پیوست محدوده اولیه',
                'verbose_name_plural': 'انواع پیوست محدوده اولیه',
            },
        ),
        migrations.CreateModel(
            name='InitialBorderDomin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('code', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'نوع محدوده اولیه',
                'verbose_name_plural': 'انواع محدوده اولیه',
            },
        ),
        migrations.CreateModel(
            name='InitialBorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('border', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('parentid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rparentinitialborder', to='initialborders.initialborder')),
                ('dtyp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rinitialborderdomin', to='initialborders.initialborderdomin')),
            ],
            options={
                'verbose_name': 'لیست محدوده اولیه',
                'verbose_name_plural': 'لیست  محدوده های اولیه',
            },
        ),
        migrations.CreateModel(
            name='InitialBorderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت پیوست')),
                ('writed_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ نوشتن پیوست')),
                ('file', models.FileField(upload_to=initialborders.models.attachment.dynamic_upload_path, verbose_name='فایل')),
                ('rinitialborder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rinitialborderachment', to='initialborders.initialborder')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_initialborderachment', to=settings.AUTH_USER_MODEL)),
                ('dtyp_attach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dtyp_initialborderattachment', to='initialborders.initialborderattachmentdomain')),
            ],
            options={
                'verbose_name': 'اتچمنت محدوده های اولیه',
                'verbose_name_plural': 'اتچمنت های محدوده های اولیه',
            },
        ),
        migrations.AddField(
            model_name='initialborderattachmentdomain',
            name='dinitialborder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rinitialborderattachmentdomin', to='initialborders.initialborderdomin'),
        ),
        migrations.CreateModel(
            name='InitialBorderMetadataDarkhastekteshaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام')),
                ('masahat', models.FloatField(blank=True, null=True, verbose_name='مساحت به کیلومترمربع')),
                ('malekiyat', models.CharField(blank=True, max_length=100, null=True, verbose_name='مالکیت')),
                ('ostan', models.CharField(blank=True, max_length=100, null=True, verbose_name='استان')),
                ('shahrestan', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهرستان')),
                ('cadastre', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره کاداستر')),
                ('noemademadani', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع ماده معدنی')),
                ('organs', models.CharField(blank=True, max_length=250, null=True, verbose_name='ارگان های استعلام شونده')),
                ('rinitialborder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rinitialborder', to='initialborders.initialborder')),
            ],
            options={
                'verbose_name': 'شناسنامه محدوده اولیه درخواست اکتشاف',
                'verbose_name_plural': 'شناسنامه محدوده اولیه درخواست اکتشاف',
            },
        ),
        migrations.CreateModel(
            name='InitialBorderMetadataGovahikashf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام')),
                ('masahat', models.FloatField(blank=True, null=True, verbose_name='مساحت به کیلومترمربع')),
                ('malekiyat', models.CharField(blank=True, max_length=100, null=True, verbose_name='مالکیت')),
                ('ostan', models.CharField(blank=True, max_length=100, null=True, verbose_name='استان')),
                ('shahrestan', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهرستان')),
                ('cadastre', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره کاداستر')),
                ('noemademadani', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع ماده معدنی')),
                ('shomareparvaneh', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره پروانه')),
                ('tarikhparvane', models.DateField(blank=True, null=True, verbose_name='تاریخ پروانه')),
                ('tarietebargovahi', models.DateField(blank=True, null=True, verbose_name='تاریخ اعتبار گواهی')),
                ('zakhireehtemali', models.FloatField(blank=True, null=True, verbose_name='ذخیره احتمالی به تن')),
                ('zakhireghatei', models.FloatField(blank=True, null=True, verbose_name='ذخیره قطعی به تن')),
                ('ayarehad', models.FloatField(blank=True, null=True, verbose_name='عیار حد به درصد')),
                ('ayaremeyangin', models.FloatField(blank=True, null=True, verbose_name='عیار میانگین به درصد')),
                ('shomaregovahikashf', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره گواهی کشف')),
                ('tarikhsodurgivahikashf', models.DateField(blank=True, null=True, verbose_name='تاریخ صدور گواهی کشف')),
                ('rinitialborder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rinitialborder', to='initialborders.initialborder')),
            ],
            options={
                'verbose_name': 'شناسنامه محدوده اولیه گواهی کشف',
                'verbose_name_plural': 'شناسنامه محدوده اولیه گواهی کشف',
            },
        ),
        migrations.CreateModel(
            name='InitialBorderMetadataPahneh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام')),
                ('masahat', models.FloatField(blank=True, null=True, verbose_name='مساحت به کیلومترمربع')),
                ('malekiyat', models.CharField(blank=True, max_length=100, null=True, verbose_name='مالکیت')),
                ('ostan', models.CharField(blank=True, max_length=100, null=True, verbose_name='استان')),
                ('shahrestan', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهرستان')),
                ('rinitialborder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rinitialborder', to='initialborders.initialborder')),
            ],
            options={
                'verbose_name': 'شناسنامه محدوده اولیه پهنه',
                'verbose_name_plural': 'شناسنامه محدوده اولیه پهنه',
            },
        ),
        migrations.CreateModel(
            name='InitialBorderMetadataParvanebahrebardai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام')),
                ('masahat', models.FloatField(blank=True, null=True, verbose_name='مساحت به کیلومترمربع')),
                ('malekiyat', models.CharField(blank=True, max_length=100, null=True, verbose_name='مالکیت')),
                ('ostan', models.CharField(blank=True, max_length=100, null=True, verbose_name='استان')),
                ('shahrestan', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهرستان')),
                ('cadastre', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره کاداستر')),
                ('noemademadani', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع ماده معدنی')),
                ('shomareparvaneh', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره پروانه')),
                ('tarikhparvane', models.DateField(blank=True, null=True, verbose_name='تاریخ پروانه')),
                ('tarietebarparvane', models.DateField(blank=True, null=True, verbose_name='تاریخ اعتبار پروانه')),
                ('zakhireehtemali', models.FloatField(blank=True, null=True, verbose_name='ذخیره احتمالی به تن')),
                ('zakhireghatei', models.FloatField(blank=True, null=True, verbose_name='ذخیره قطعی به تن')),
                ('ayarehad', models.FloatField(blank=True, null=True, verbose_name='عیار حد به درصد')),
                ('ayaremeyangin', models.FloatField(blank=True, null=True, verbose_name='عیار میانگین به درصد')),
                ('estekhrajsaleyane', models.FloatField(blank=True, null=True, verbose_name=' استخراج سالیانه به تن')),
                ('rinitialborder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rinitialborder', to='initialborders.initialborder')),
            ],
            options={
                'verbose_name': 'شناسنامه محدوده اولیه پروانه بهره برداری',
                'verbose_name_plural': 'شناسنامه محدوده اولیه پروانه بهره برداری',
            },
        ),
        migrations.CreateModel(
            name='InitialBorderMetadataParvaneekteshaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام')),
                ('masahat', models.FloatField(blank=True, null=True, verbose_name='مساحت به کیلومترمربع')),
                ('malekiyat', models.CharField(blank=True, max_length=100, null=True, verbose_name='مالکیت')),
                ('ostan', models.CharField(blank=True, max_length=100, null=True, verbose_name='استان')),
                ('shahrestan', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهرستان')),
                ('cadastre', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره کاداستر')),
                ('noemademadani', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع ماده معدنی')),
                ('shomareparvaneh', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره پروانه')),
                ('tarikhparvane', models.DateField(blank=True, null=True, verbose_name='تاریخ پروانه')),
                ('tarikhetebar', models.DateField(blank=True, null=True, verbose_name='تاریخ اعتبار')),
                ('rinitialborder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rinitialborder', to='initialborders.initialborder')),
            ],
            options={
                'verbose_name': 'شناسنامه محدوده اولیه پروانه اکتشاف',
                'verbose_name_plural': 'شناسنامه محدوده اولیه پروانه اکتشاف',
            },
        ),
        migrations.CreateModel(
            name='InitialBorderMetadataPotansielyabi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام')),
                ('masahat', models.FloatField(blank=True, null=True, verbose_name='مساحت به کیلومترمربع')),
                ('malekiyat', models.CharField(blank=True, max_length=100, null=True, verbose_name='مالکیت')),
                ('ostan', models.CharField(blank=True, max_length=100, null=True, verbose_name='استان')),
                ('shahrestan', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهرستان')),
                ('noemademadani', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع ماده معدنی')),
                ('rinitialborder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rinitialborder', to='initialborders.initialborder')),
            ],
            options={
                'verbose_name': 'شناسنامه محدوده اولیه پتانسیل یابی',
                'verbose_name_plural': 'شناسنامه محدوده قانواولیهنی پتانسیل یابی',
            },
        ),
    ]
