# Generated by Django 5.2 on 2025-07-20 11:46

import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initialborders', '0001_firsttabels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialborder',
            name='border',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
        migrations.AlterField(
            model_name='initialborder',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
