# Generated by Django 5.2 on 2025-09-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_create_county_model'),
        ('initialborders', '0002_maketitlesnallfalse'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialborder',
            name='province',
            field=models.ManyToManyField(blank=True, related_name='rprovinceinitialborder', to='common.province', verbose_name='استان'),
        ),
    ]
