# Generated by Django 5.2 on 2025-07-26 07:19

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('initialborders', '0002_maketitlesnallfalse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDomin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('code', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'نوع قرادادها',
                'verbose_name_plural': 'انواع قرادادها',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(error_messages={'unique': 'قراردادی با این عنوان هم\u200cاکنون وجود دارد'}, max_length=250, unique=True, verbose_name='عنوان قرارداد')),
                ('number', models.CharField(blank=True, error_messages={'unique': 'شماره قرارداد تکراری است'}, max_length=100, null=True, unique=True, verbose_name='شماره قرارداد')),
                ('province', models.CharField(blank=True, max_length=50, null=True, verbose_name='استان')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('progress', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, message='پیشرفت نمی\u200cتواند کمتر از صفر باشد.'), django.core.validators.MaxValueValidator(100, message='پیشرفت نمی\u200cتواند بیشتر از صد باشد.')], verbose_name='پیشرفت (درصد)')),
                ('is_completed', models.BooleanField(db_index=True, default=False, verbose_name='خاتمه یافته')),
                ('department', models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='بخش مربوطه')),
                ('elhaghye', models.BooleanField(default=False, verbose_name='الحاقیه دارد')),
                ('mablagh', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='مبلغ قرارداد نمی\u200cتواند کمتر از صفر باشد.')], verbose_name='مبلغ قرارداد')),
                ('mablaghe_elhaghye', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='مبلغ الحاقیه نمی\u200cتواند کمتر از صفر باشد.')], verbose_name='مبلغ الحاقیه')),
                ('tarikh_elhaghye', models.DateField(blank=True, null=True, verbose_name='تاریخ الحاقیه')),
                ('initborder', models.ManyToManyField(related_name='rinitcontracts', to='initialborders.initialborder', verbose_name='محدوده اولیه')),
                ('dtyp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rdtypcontracts', to='contracts.contractdomin', verbose_name='نوع قرارداد')),
            ],
            options={
                'verbose_name': 'قراداد',
                'verbose_name_plural': 'قرادادها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractBorder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('border', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rcontractborders', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'محدوده قراداد',
                'verbose_name_plural': 'محدوده قرادادها',
            },
        ),
    ]
