# Generated by Django 5.2 on 2025-07-28 08:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial_contracts_models'),
        ('layers', '0001_create_layernames_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShrhBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان بند شرح خدمات')),
                ('unit', models.CharField(max_length=100, verbose_name='واحد')),
                ('weight', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='وزن بند')),
                ('total_volume', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='حجم کل بند')),
                ('worked_volume', models.PositiveIntegerField(default=0, verbose_name='حجم کار شده')),
                ('unit_price', models.PositiveBigIntegerField(default=0, verbose_name='قیمت واحد')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shrh_items', to='contracts.contract', verbose_name='قرارداد')),
            ],
            options={
                'verbose_name': 'بند  شرخ\u200cخدمات',
                'verbose_name_plural': 'بندهای شرح\u200cخدمات',
            },
        ),
        migrations.CreateModel(
            name='ShrhLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('raster_uuid', models.CharField(blank=True, max_length=100, null=True, verbose_name='raster uuid')),
                ('scale', models.CharField(blank=True, choices=[('1:250000', '1:250000'), ('1:100000', '1:100000'), ('1:50000', '1:50000'), ('1:25000', '1:25000'), ('1:10000', '1:10000'), ('1:5000', '1:5000'), ('1:2000', '1:2000'), ('1:1000', '1:1000'), ('1:500', '1:500'), ('1:<500', '1:<500')], max_length=20, null=True, verbose_name='مقیاس')),
                ('is_uploaded', models.BooleanField(default=False, verbose_name='بارگذاری شده')),
                ('last_uploaded_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ آخرین بارگذاری')),
                ('upload_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دفعات بارگذاری')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید نهایی')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تاییدنهایی شده')),
                ('layer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_shrlyrs', to='layers.layersnames')),
                ('shrh_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shr_layers', to='contracts.shrhbase')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_shrh_layers', to=settings.AUTH_USER_MODEL, verbose_name='کاربر تاییدنهایی کننده')),
            ],
            options={
                'verbose_name': 'لایه شرح خدمات',
                'verbose_name_plural': 'لایه\u200cهای شرح خدمات',
                'ordering': ['shrh_base', 'layer_name'],
            },
        ),
        migrations.AddIndex(
            model_name='shrhbase',
            index=models.Index(fields=['contract'], name='contracts_s_contrac_e43129_idx'),
        ),
    ]
