# Generated by Django 5.2 on 2025-08-09 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_init_sharhkhadamat_tabels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('text', models.TextField(max_length=500, verbose_name='متن')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='contracts.comment', verbose_name='نظر قبلی')),
                ('sharhlayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rcomments', to='contracts.shrhlayer', verbose_name='لایه شرح خدمات')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruser_comments', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sharhlayer', '-created_at'], name='contracts_c_sharhla_41249e_idx'), models.Index(fields=['writer', '-created_at'], name='contracts_c_writer__397841_idx'), models.Index(fields=['parent', '-created_at'], name='contracts_c_parent__296469_idx')],
            },
        ),
    ]
