# Generated by Django 5.2 on 2025-08-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_create_province_model'),
        ('contracts', '0003_add_comment_tabel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='province',
        ),
        migrations.AddField(
            model_name='contract',
            name='province',
            field=models.ManyToManyField(blank=True, related_name='rprovincecontracts', to='common.province', verbose_name='استان'),
        ),
    ]
