# Generated by Django 5.2 on 2025-08-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_add_company_to_user'),
        ('contracts', '0004_province_m2m_in_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='company',
            field=models.ManyToManyField(blank=True, related_name='rcompanycontracts', to='common.company', verbose_name='شرکت'),
        ),
    ]
