# Generated by Django 5.2 on 2025-09-07 10:26

import contracts.models.attachment
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_company_m2m_in_contract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractBorderAttachmentDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('code', models.IntegerField(unique=True, verbose_name='کد')),
                ('name_en', models.CharField(max_length=100, verbose_name='نام لاتین')),
                ('name_fa', models.CharField(max_length=100, verbose_name='نام فارسی')),
                ('typ', models.CharField(max_length=100, verbose_name='نوع')),
            ],
            options={
                'verbose_name': 'نوع پیوست محدوده قرارداد',
                'verbose_name_plural': 'انواع پیوست محدوده قرارداد',
            },
        ),
        migrations.CreateModel(
            name='ContractBorderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('file', models.FileField(upload_to=contracts.models.attachment.dynamic_upload_path, verbose_name='فایل')),
                ('contractborder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rcontractborderattachment', to='contracts.contractborder')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_contractborderattachment', to=settings.AUTH_USER_MODEL)),
                ('dtyp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dtyp_contractborderattachment', to='contracts.contractborderattachmentdomain')),
            ],
            options={
                'verbose_name': 'اتچمنت پروژه',
                'verbose_name_plural': 'اتچمنت های پروژه',
            },
        ),
    ]
