# Generated by Django 5.2 on 2025-09-07 10:38

import contracts.models.attachment
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_create_attach_contract_border'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractborderattachment',
            options={'verbose_name': 'پیوست محودوه قرارداد', 'verbose_name_plural': 'پیوست\u200cهای محدوده قرارداد'},
        ),
        migrations.AlterField(
            model_name='contractborderattachment',
            name='file',
            field=models.FileField(max_length=500, upload_to=contracts.models.attachment.dynamic_upload_path, verbose_name='فایل'),
        ),
    ]
