# Generated by Django 5.2 on 2025-09-08 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_increase_filename_length_attach_contract_border'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shrhbase',
            name='total_volume',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='حجم کل بند'),
        ),
        migrations.AlterField(
            model_name='shrhbase',
            name='unit',
            field=models.CharField(choices=[('تعداد', 'تعداد'), ('هکتار', 'هکتار'), ('نفرماه', 'نفرماه'), ('متراژ', 'متراژ'), ('کیلومترمربع', 'کیلومترمربع')], max_length=100, verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='shrhbase',
            name='weight',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='وزن بند'),
        ),
    ]
