# Generated by Django 5.2 on 2025-09-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_enhance_shrhbase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='department',
            field=models.CharField(blank=True, choices=[(1, 'خدمات مشاوره ایی'), (2, 'حفاری'), (3, 'ژئوفیزیک'), (4, 'چاه پیمایی'), (5, 'آزمایشگاه')], default='-', max_length=100, null=True, verbose_name='بخش مربوطه'),
        ),
    ]
