# Generated by Django 5.2 on 2025-09-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_del_m2mrel_initborder_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='province',
        ),
    ]
