# Generated by Django 5.2 on 2025-09-14 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_del_m2mrel_province_contract'),
        ('initialborders', '0003_add_m2mrel_initialborder_prviance'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractborder',
            name='initborder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rinitcontractborders', to='initialborders.initialborder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractborder',
            name='scale',
            field=models.CharField(blank=True, choices=[('1:250000', '1:250000'), ('1:100000', '1:100000'), ('1:50000', '1:50000'), ('1:25000', '1:25000'), ('1:10000', '1:10000'), ('1:5000', '1:5000'), ('1:2000', '1:2000'), ('1:1000', '1:1000'), ('1:500', '1:500'), ('1:<500', '1:<500')], max_length=20, null=True, verbose_name='مقیاس'),
        ),
        migrations.AddField(
            model_name='contractborder',
            name='title',
            field=models.CharField(default='default', max_length=250, verbose_name='عنوان محدوده قرارداد'),
            preserve_default=False,
        ),
    ]
