# Generated by Django 5.2 on 2025-09-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_add_rel_initialborder_contractborder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractborder',
            name='scale',
            field=models.IntegerField(blank=True, choices=[(250000, '1:250000'), (100000, '1:100000'), (50000, '1:50000'), (25000, '1:25000'), (10000, '1:10000'), (5000, '1:5000'), (2000, '1:2000'), (1000, '1:1000'), (500, '1:500'), (499, '1:<500')], null=True, verbose_name='مقیاس'),
        ),
        migrations.AlterField(
            model_name='shrhlayer',
            name='scale',
            field=models.IntegerField(blank=True, choices=[(250000, '1:250000'), (100000, '1:100000'), (50000, '1:50000'), (25000, '1:25000'), (10000, '1:10000'), (5000, '1:5000'), (2000, '1:2000'), (1000, '1:1000'), (500, '1:500'), (499, '1:<500')], null=True, verbose_name='مقیاس'),
        ),
    ]
