# Generated by Django 5.2 on 2025-09-16 06:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_chng_scale_to_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='shrhlayer',
            name='contractborder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rcontractborderlayers', to='contracts.contractborder'),
        ),
        migrations.AddField(
            model_name='shrhlayer',
            name='layer_volume',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حجم لایه'),
        ),
        migrations.AddField(
            model_name='shrhlayer',
            name='layer_weight',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='وزن لایه'),
        ),
        migrations.AlterField(
            model_name='shrhbase',
            name='total_volume',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حجم کل بند'),
        ),
        migrations.AlterField(
            model_name='shrhbase',
            name='weight',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='وزن بند'),
        ),
    ]
