# Generated by Django 5.2 on 2025-09-16 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_add_shrlyr_newfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shrhlayer',
            name='contractborder',
            field=models.ForeignKey(default='c7d4c4c0-cccb-4de9-86bd-1bc045b97e59', on_delete=django.db.models.deletion.CASCADE, related_name='rcontractborderlayers', to='contracts.contractborder'),
            preserve_default=False,
        ),
    ]
