# Generated by Django 5.2 on 2025-09-20 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_make_conbrdr_in_shrlyr_notnull'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shrhlayer',
            name='last_uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploader_shrh_layers', to=settings.AUTH_USER_MODEL, verbose_name='کاربر بارگذاری کننده'),
        ),
    ]
