# Generated by Django 5.2 on 2025-11-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0016_add_shrhlayer_last_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='department',
            field=models.CharField(blank=True, choices=[('1', 'خدمات مشاوره ایی'), ('2', 'حفاری'), ('3', 'ژئوفیزیک'), ('4', 'چاه پیمایی'), ('5', 'آزمایشگاه')], default='-', error_messages={'invalid_choice': 'انتخاب نامعتبر است. گزینه\u200cهای معتبر: 1 (خدمات مشاوره ایی), 2 (حفاری), 3 (ژئوفیزیک), 4 (چاه پیمایی), 5 (آزمایشگاه)'}, max_length=100, null=True, verbose_name='بخش مربوطه'),
        ),
    ]
