# Generated by Django 5.2 on 2025-12-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_user_objectlevel_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='oldid',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='contractborder',
            name='oldid',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
