# Generated by Django 5.2 on 2025-12-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0018_add_oldid_to_cntrct_cntrctbrdr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractborder',
            name='oldid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
