# Generated by Django 5.2 on 2025-12-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0019_not_unique_oldid_cntrctbrdr'),
    ]

    operations = [
        migrations.AddField(
            model_name='shrhlayer',
            name='oldid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
