# Generated by Django 5.2 on 2025-07-28 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial_contracts_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayersNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lyrgroup_en', models.CharField(blank=True, max_length=40, null=True)),
                ('lyrgroup_fa', models.CharField(blank=True, max_length=40, null=True)),
                ('layername_en', models.CharField(blank=True, max_length=40, null=True)),
                ('layername_fa', models.CharField(blank=True, max_length=40, null=True)),
                ('geometrytype', models.CharField(blank=True, max_length=20, null=True)),
                ('dtyp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rlyrnamedtyp', to='contracts.contractdomin')),
            ],
            options={
                'verbose_name': 'لیست نام لایه ها',
                'verbose_name_plural': 'لیست نام لایه ها',
            },
        ),
    ]
