# Generated by Django 5.2 on 2025-08-10 06:03

import django.db.models.deletion
import layers.models.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('layers', '0002_create_layernames_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ساخت')),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('file', models.FileField(upload_to=layers.models.models.dynamic_upload_path, validators=[layers.models.models.validate_file_size], verbose_name='فایل')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_featureattachment', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'اتچمنت عارضه',
                'verbose_name_plural': 'اتچمنت های عارضه',
                'ordering': ['-upload_date'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='layers_feat_content_78ec29_idx'), models.Index(fields=['-upload_date'], name='layers_feat_upload__9589ca_idx')],
            },
        ),
    ]
