# Generated by Django 5.2 on 2025-12-09 09:32

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_user_objectlevel_permission'),
        ('layers', '0003_create_featureattachment_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extraction_Bench_Mark_Pt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='نام یا شماره')),
                ('typ', models.CharField(blank=True, max_length=250, null=True, verbose_name='نوع')),
                ('elevation', models.FloatField(blank=True, null=True, verbose_name='ارتفاع')),
                ('border', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('shr_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rshrlayer', to='contracts.shrhlayer')),
            ],
            options={
                'verbose_name': 'ایستگاه نقشه برداری',
                'verbose_name_plural': 'ایستگاه نقشه برداری',
            },
        ),
        migrations.CreateModel(
            name='Extraction_Block_Pg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_blast', models.CharField(blank=True, max_length=200, null=True, verbose_name='شناسه هر مرحله انفجار')),
                ('blast_n', models.FloatField(blank=True, null=True, verbose_name='تعداد اتشباری')),
                ('hole_n', models.FloatField(blank=True, null=True, verbose_name='تعداد چال')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='مقدار مواد منفجره مصرفی')),
                ('date', models.CharField(blank=True, max_length=250, null=True, verbose_name='تاریخ ')),
                ('tonag', models.FloatField(blank=True, null=True, verbose_name='تناژ عملکرد انفجار')),
                ('special_expense', models.FloatField(blank=True, null=True, verbose_name='خرج ویژه')),
                ('w_density', models.FloatField(blank=True, null=True, verbose_name='وزن مخصوص سنگ')),
                ('rock_density', models.FloatField(blank=True, null=True, verbose_name='وزن مخصوص باطله')),
                ('comment', models.CharField(blank=True, max_length=250, null=True, verbose_name='توضیحات ')),
                ('border', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('shr_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rshrlayer', to='contracts.shrhlayer')),
            ],
            options={
                'verbose_name': 'بلوک استخراج',
                'verbose_name_plural': 'بلوک استخراج',
            },
        ),
        migrations.CreateModel(
            name='Extraction_Mine_Dump_Pg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depo_n', models.CharField(blank=True, max_length=250, null=True, verbose_name='شناسه  هر دپو')),
                ('volume_mine', models.FloatField(blank=True, null=True, verbose_name='حجم باطله')),
                ('survey_date', models.CharField(blank=True, max_length=250, null=True, verbose_name='تاریخ نقشه برداری')),
                ('comment', models.CharField(blank=True, max_length=250, null=True, verbose_name='توضیحات')),
                ('border', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('shr_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rshrlayer', to='contracts.shrhlayer')),
            ],
            options={
                'verbose_name': 'دامپ ماده معدنی',
                'verbose_name_plural': 'دامپ ماده معدنی',
            },
        ),
        migrations.CreateModel(
            name='Extraction_Mine_Dump_Pl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depo_n', models.CharField(blank=True, max_length=250, null=True, verbose_name='شناسه  هر دپو')),
                ('volume_mine', models.FloatField(blank=True, null=True, verbose_name='حجم باطله')),
                ('survey_date', models.CharField(blank=True, max_length=250, null=True, verbose_name='تاریخ نقشه برداری')),
                ('comment', models.CharField(blank=True, max_length=250, null=True, verbose_name='توضیحات')),
                ('border', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('shr_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rshrlayer', to='contracts.shrhlayer')),
            ],
            options={
                'verbose_name': 'دامپ ماده معدنی',
                'verbose_name_plural': 'دامپ ماده معدنی',
            },
        ),
        migrations.CreateModel(
            name='Extraction_Mine_Dump_Pt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depo_n', models.CharField(blank=True, max_length=250, null=True, verbose_name='شناسه  هر دپو')),
                ('volume_mine', models.FloatField(blank=True, null=True, verbose_name='حجم باطله')),
                ('survey_date', models.CharField(blank=True, max_length=250, null=True, verbose_name='تاریخ نقشه برداری')),
                ('comment', models.CharField(blank=True, max_length=250, null=True, verbose_name='توضیحات')),
                ('border', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('shr_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rshrlayer', to='contracts.shrhlayer')),
            ],
            options={
                'verbose_name': 'دامپ ماده معدنی',
                'verbose_name_plural': 'دامپ ماده معدنی',
            },
        ),
        migrations.CreateModel(
            name='Extraction_Operation_Drilling_Pg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_drill', models.CharField(blank=True, max_length=250, null=True, verbose_name='شناسه حفاری')),
                ('method', models.CharField(blank=True, max_length=250, null=True, verbose_name='روش حفاری')),
                ('drilling_type', models.CharField(blank=True, max_length=250, null=True, verbose_name='نوع حفاری')),
                ('excavator', models.CharField(blank=True, max_length=250, null=True, verbose_name='مجری حفاری')),
                ('depth', models.FloatField(blank=True, null=True, verbose_name='عمق')),
                ('diameter', models.FloatField(blank=True, null=True, verbose_name='قطر')),
                ('dip', models.FloatField(blank=True, null=True, verbose_name='شیب حفاری')),
                ('drilling_cost', models.FloatField(blank=True, null=True, verbose_name='هزینه حفاری')),
                ('drilling_date', models.FloatField(blank=True, null=True, verbose_name='تاریخ انجام حفاری')),
                ('volume', models.FloatField(blank=True, null=True, verbose_name='حجم استخراج')),
                ('w_Density', models.FloatField(blank=True, null=True, verbose_name='وزن مخصوص باطله')),
                ('rock_density', models.FloatField(blank=True, null=True, verbose_name='وزن مخصوص سنگ ')),
                ('comment', models.CharField(blank=True, max_length=250, null=True, verbose_name='توضیحات ')),
                ('border', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('shr_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rshrlayer', to='contracts.shrhlayer')),
            ],
            options={
                'verbose_name': 'عملیات اجرای حفاری',
                'verbose_name_plural': 'عملیات اجرای حفاری',
            },
        ),
        migrations.CreateModel(
            name='Extraction_Operation_Drilling_Pl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_drill', models.CharField(blank=True, max_length=250, null=True, verbose_name='شناسه حفاری')),
                ('method', models.CharField(blank=True, max_length=250, null=True, verbose_name='روش حفاری')),
                ('drilling_type', models.CharField(blank=True, max_length=250, null=True, verbose_name='نوع حفاری')),
                ('excavator', models.CharField(blank=True, max_length=250, null=True, verbose_name='مجری حفاری')),
                ('depth', models.FloatField(blank=True, null=True, verbose_name='عمق')),
                ('diameter', models.FloatField(blank=True, null=True, verbose_name='قطر')),
                ('dip', models.FloatField(blank=True, null=True, verbose_name='شیب حفاری')),
                ('drilling_cost', models.FloatField(blank=True, null=True, verbose_name='هزینه حفاری')),
                ('drilling_date', models.FloatField(blank=True, null=True, verbose_name='تاریخ انجام حفاری')),
                ('volume', models.FloatField(blank=True, null=True, verbose_name='حجم استخراج')),
                ('w_Density', models.FloatField(blank=True, null=True, verbose_name='وزن مخصوص باطله')),
                ('rock_density', models.FloatField(blank=True, null=True, verbose_name='وزن مخصوص سنگ ')),
                ('comment', models.CharField(blank=True, max_length=250, null=True, verbose_name='توضیحات ')),
                ('border', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('shr_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rshrlayer', to='contracts.shrhlayer')),
            ],
            options={
                'verbose_name': 'عملیات اجرای حفاری',
                'verbose_name_plural': 'عملیات اجرای حفاری',
            },
        ),
        migrations.CreateModel(
            name='Extraction_Operation_Drilling_Pt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_drill', models.CharField(blank=True, max_length=250, null=True, verbose_name='شناسه حفاری')),
                ('method', models.CharField(blank=True, max_length=250, null=True, verbose_name='روش حفاری')),
                ('drilling_type', models.CharField(blank=True, max_length=250, null=True, verbose_name='نوع حفاری')),
                ('excavator', models.CharField(blank=True, max_length=250, null=True, verbose_name='مجری حفاری')),
                ('depth', models.FloatField(blank=True, null=True, verbose_name='عمق')),
                ('diameter', models.FloatField(blank=True, null=True, verbose_name='قطر')),
                ('dip', models.FloatField(blank=True, null=True, verbose_name='شیب حفاری')),
                ('drilling_cost', models.FloatField(blank=True, null=True, verbose_name='هزینه حفاری')),
                ('drilling_date', models.FloatField(blank=True, null=True, verbose_name='تاریخ انجام حفاری')),
                ('volume', models.FloatField(blank=True, null=True, verbose_name='حجم استخراج')),
                ('w_Density', models.FloatField(blank=True, null=True, verbose_name='وزن مخصوص باطله')),
                ('rock_density', models.FloatField(blank=True, null=True, verbose_name='وزن مخصوص سنگ ')),
                ('comment', models.CharField(blank=True, max_length=250, null=True, verbose_name='توضیحات ')),
                ('border', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('shr_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rshrlayer', to='contracts.shrhlayer')),
            ],
            options={
                'verbose_name': 'عملیات اجرای حفاری',
                'verbose_name_plural': 'عملیات اجرای حفاری',
            },
        ),
    ]
