# Generated by Django 5.2 on 2025-12-10 10:17

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_user_objectlevel_permission'),
        ('layers', '0004_add_new_extraction_layer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory_Pelan_Pg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='نام')),
                ('border', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('shr_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rshrlayer', to='contracts.shrhlayer')),
            ],
            options={
                'verbose_name': 'پلان',
                'verbose_name_plural': 'پلان',
            },
        ),
        migrations.CreateModel(
            name='Factory_Pelan_Pl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='نام')),
                ('border', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('shr_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rshrlayer', to='contracts.shrhlayer')),
            ],
            options={
                'verbose_name': 'پلان',
                'verbose_name_plural': 'پلان',
            },
        ),
        migrations.CreateModel(
            name='Factory_Pelan_Pt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='نام')),
                ('border', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('shr_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rshrlayer', to='contracts.shrhlayer')),
            ],
            options={
                'verbose_name': 'پلان',
                'verbose_name_plural': 'پلان',
            },
        ),
    ]
