# Generated by Django 4.2.5 on 2025-04-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarikh', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('writer', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], max_length=25)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('OTHER', 'OTHER')], max_length=25)),
                ('route', models.CharField(blank=True, max_length=100, null=True)),
                ('massage', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'لاگ',
                'verbose_name_plural': 'لیست لاگ ها',
            },
        ),
    ]
