# Generated by Django 4.2.5 on 2025-07-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_init_table_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='massage',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
