# Generated by Django 5.2 on 2025-08-12 05:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(unique=True, verbose_name='نام')),
                ('cnter_name_fa', models.CharField(unique=True, verbose_name='نام مرکز')),
                ('code', models.PositiveIntegerField(unique=True, verbose_name='کد')),
                ('border', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان ها',
            },
        ),
    ]
