# Generated by Django 5.2 on 2025-08-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_create_province_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام شرکت')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد شناسایی شرکت')),
                ('typ', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع شرکت')),
                ('service_typ', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع خدمات')),
                ('callnumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره تماس')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'لیست شرکت',
                'verbose_name_plural': 'لیست شرکت های',
            },
        ),
    ]
