# Generated by Django 5.2 on 2025-08-12 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_create_company_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'لیست شرکت', 'verbose_name_plural': 'لیست شرکت ها'},
        ),
    ]
