# Generated by Django 5.2 on 2025-08-16 06:56

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_add_company_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(unique=True, verbose_name='نام')),
                ('code', models.PositiveIntegerField(unique=True, verbose_name='کد')),
                ('border', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rprovince', to='common.province')),
            ],
            options={
                'verbose_name': 'شهرستان',
                'verbose_name_plural': 'شهرستان ها',
            },
        ),
    ]
