# Generated by Django 5.2 on 2025-12-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_create_county_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(error_messages={'unique': 'شرکتی با این نام قبلاً ثبت شده است.'}, max_length=100, unique=True, verbose_name='نام شرکت'),
        ),
    ]
